local mMT, DB, M, E, P, L, MEDIA = unpack(ElvUI_mMediaTag)

-- system settings
P.db_version = nil

-- general
P.general = {
	greeting_message = true,
}

-- general
P.keystone_to_chat = {
	enable = true,
}

-- data panel skin
P.data_panel_skin = {
	enable = false,
	panels = {},
}

-- dice button
P.dice_button = {
	enable = false,
	color = {
		normal = {
			mode = "custom",
			color = { r = 1, g = 1, b = 1, a = 0.75 },
		},
		hover = {
			mode = "class",
			color = { r = 1, g = 1, b = 1, a = 0.75 },
		},
	},
	texture = "dice05",
	size = 16,
	dice_range_a = 100,
	dice_range_b = 99,
}

-- lfg invite info
P.lfg_invite_info = {
	enable = false,
	delay = 60,
	icon = "none",
	font = {
		font = "PT Sans Narrow",
		size = 32,
		size2 = 22,
		fontflag = "OUTLINE",
	},
	colors = {
		line_a = "FFFFBF00",
		line_b = "FF9AA0A5",
		line_c = "FFA335EE",
	},
}

-- map icon highlighter
P.map_icon_highlighter = {
	enable = true,
	globalScale = 1,
	globalTextSize = 12,
	globalTextFont = "PT Sans Narrow",
	globalTextOutline = "OUTLINE",
	delves = {
		iconScale = 1,
		hlShow = true,
		hlScale = 1,
		hlColorEnable = true,
	},
	delvesBountiful = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	caveExitUp = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	caveExitDown = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	zonePortalNeutral = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	zonePortalAlliance = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	zonePortalHorde = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	flightpoint = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	flightpointUnknown = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	poiHub = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	wqAssignmentLocked = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	dungeon = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	raid = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	waypoint = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	scrapHeap_active = {
	iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
	scrapHeap_inactive = {
		iconScale = 1,
		enable = true,
		scale = 1,
		use_color = true,
		color = { r = 1, g = 1, b = 1 },
		alpha = 1,
		style = 1,
		show_text = true,
		custom_font = false,
		font = "PT Sans Narrow",
		fontflag = "OUTLINE",
		textPosition = 1,
		textScale = 1,
		text_color = { r = 1, g = 1, b = 1 },
		text_alpha = 1,
	},
}

-- datatexts
P.datatexts = {
	text = {
		override_text = true,
		text = "FFFFFFFF",
		override_value = false,
		value = "FFFFFFFF",
	},
	score = {
		group_keystones = true,
		show_upgrade = true,
		sort_method = "KEY",
	},
	teleports = {
		icon = "teleport04",
		favorites = {
			enable = false,
			a = { id = "none", kind = "none" },
			b = { id = "none", kind = "none" },
			c = { id = "none", kind = "none" },
			d = { id = "none", kind = "none" },
		},
	},
	individual_professions = {
		icon = "default",
	},
	professions = {
		icon = "prof_a",
		menu_icons = "default",
	},
	menu = {
		icon = "mmt",
		menu_icons = true,
		show_systeminfo = true,
	},
	tracker = {
		custom = {},
		hide_if_zero = false,
		icon = true,
		name = false,
		short_number = true,
		show_max = false,
		colored = true,
	},
	combat_time = {
		in_combat = "combat_02",
		out_of_combat = "combat_13",
		hide_delay = 5,
	},
}

-- media
P.media = {
	color = {
		title = "FFFFBE19",
		text = "FFFFFFFF",
		tip = "FFB2B2B2",
		mark = "FF38FF92",
	},
}
