local mMT, E, L, V, P, G = unpack((select(2, ...)))

mMT.Media.CombatIcons = {
	CI1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat1.tga",
	CI2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat2.tga",
	CI3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat3.tga",
	CI4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat4.tga",
	CI5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat5.tga",
	CI6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat6.tga",
	CI7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat7.tga",
	CI8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat8.tga",
	CI9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat9.tga",
	CI10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat10.tga",
	CI12 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\combat11.tga",
}

mMT.Media.RollIcons = {
	RI1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\roll\\roll1.tga",
	RI2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\roll\\roll2.tga",
	RI3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\roll\\roll3.tga",
	RI4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\roll\\roll4.tga",
}

mMT.Media.ChatIcons = {
	CI1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\chat\\chat1.tga",
	CI2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\chat\\chat2.tga",
	CI3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\chat\\chat3.tga",
	CI4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\chat\\chat4.tga",
	CI5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\chat\\chat5.tga",
	CI6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\chat\\chat6.tga",
	CI7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\chat\\chat7.tga",
	CI8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\chat\\chat8.tga",
}

mMT.Media.UpgradeIcons = {
	UI1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\upgrade1.tga",
	UI2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\upgrade2.tga",
	UI3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\upgrade3.tga",
	UI4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\upgrade4.tga",
	UI5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\upgrade5.tga",
	UI6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\upgrade6.tga",
	UI7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\datatext\\upgrade7.tga",
}

mMT.Media.Mous = {
	LEFT = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\system\\mleft.tga",
	MIDDLE = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\system\\mmiddle.tga",
	RIGHT = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\system\\mright.tga",
}

mMT.Media.Role = {
	SHIELD1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield1.tga",
	SHIELD2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield2.tga",
	SHIELD3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield3.tga",
	SHIELD4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield4.tga",
	SHIELD5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield5.tga",
	SHIELD6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield6.tga",
	SHIELD7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield7.tga",
	SHIELD8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield8.tga",
	SHIELD9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield9.tga",
	SHIELD10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield10.tga",
	SHIELD11 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shield11.tga",

	SHIELDOUT1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shieldoutliner1.tga",
	SHIELDOUT2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shieldoutliner2.tga",
	SHIELDOUT3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shieldoutliner3.tga",
	SHIELDOUT4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shieldoutliner4.tga",
	SHIELDOUT5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shieldoutliner5.tga",
	SHIELDOUT6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shieldoutliner6.tga",
	SHIELDOUT7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\shieldoutliner7.tga",

	HEAL1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal1.tga",
	HEAL2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal2.tga",
	HEAL3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal3.tga",
	HEAL4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal4.tga",
	HEAL5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal5.tga",
	HEAL6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal6.tga",
	HEAL7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal7.tga",
	HEAL8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal8.tga",
	HEAL9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal9.tga",
	HEAL10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal10.tga",
	HEAL11 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal11.tga",
	HEAL12 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal12.tga",
	HEAL13 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal13.tga",
	HEAL14 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heal14.tga",

	HEALOUT1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\healoutline1.tga",
	HEALOUT2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\healoutline2.tga",
	HEALOUT3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\healoutline3.tga",
	HEALOUT4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\healoutline4.tga",
	HEALOUT5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\healoutline5.tga",
	HEALOUT6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\healoutline6.tga",

	BIGSW1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword1.tga",
	BIGSW2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword2.tga",
	BIGSW3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword3.tga",
	BIGSW4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword4.tga",
	BIGSW5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword5.tga",
	BIGSW6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword6.tga",
	BIGSW7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword7.tga",
	BIGSW8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword8.tga",
	BIGSW9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword9.tga",
	BIGSW10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword10.tga",
	BIGSW11 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword11.tga",
	BIGSW12 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword12.tga",
	BIGSW13 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword13.tga",
	BIGSW14 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword14.tga",
	BIGSW15 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\bigsword15.tga",

	COKIE1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie1.tga",
	COKIE2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie2.tga",
	COKIE3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie3.tga",
	COKIE4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie4.tga",
	COKIE5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie5.tga",
	COKIE6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie6.tga",
	COKIE7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie7.tga",
	COKIE8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie8.tga",
	COKIE9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie9.tga",
	COKIE10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie10.tga",
	COKIE11 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie11.tga",
	COKIE12 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie12.tga",
	COKIE13 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie13.tga",
	COKIE14 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\cookie14.tga",

	DROP1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop1.tga",
	DROP2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop2.tga",
	DROP3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop3.tga",
	DROP4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop4.tga",
	DROP5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop5.tga",
	DROP6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop6.tga",
	DROP7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop7.tga",
	DROP8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop8.tga",
	DROP9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop9.tga",
	DROP10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop10.tga",
	DROP11 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop11.tga",
	DROP12 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\drop12.tga",

	FIRE1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\fire1.tga",
	FIRE2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\fire2.tga",
	FIRE3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\fire3.tga",
	FIRE4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\fire4.tga",
	FIRE5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\fire5.tga",

	HEART1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart1.tga",
	HEART2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart2.tga",
	HEART3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart3.tga",
	HEART4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart4.tga",
	HEART5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart5.tga",
	HEART6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart6.tga",
	HEART7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart7.tga",
	HEART8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart8.tga",
	HEART9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart9.tga",
	HEART10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart10.tga",
	HEART11 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart11.tga",
	HEART12 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\heart12.tga",

	LIGHTN1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning1.tga",
	LIGHTN2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning2.tga",
	LIGHTN3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning3.tga",
	LIGHTN4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning4.tga",
	LIGHTN5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning5.tga",
	LIGHTN6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning6.tga",
	LIGHTN7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning7.tga",
	LIGHTN8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning8.tga",
	LIGHTN9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning9.tga",
	LIGHTN10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\lightning10.tga",

	MOON1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\moon1.tga",
	MOON2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\moon2.tga",
	MOON3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\moon3.tga",
	MOON4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\moon4.tga",
	MOON5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\moon5.tga",
	MOON6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\moon6.tga",
	MOON7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\moon7.tga",
	MOON8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\moon8.tga",

	STAR1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star1.tga",
	STAR2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star10.tga",
	STAR3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star2.tga",
	STAR4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star3.tga",
	STAR5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star4.tga",
	STAR6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star5.tga",
	STAR7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star6.tga",
	STAR8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star7.tga",
	STAR9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star8.tga",
	STAR10 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\star9.tga",

	SWORD1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword1.tga",
	SWORD2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword2.tga",
	SWORD3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword3.tga",
	SWORD4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword4.tga",
	SWORD5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword5.tga",
	SWORD6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword6.tga",
	SWORD7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword7.tga",
	SWORD8 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword8.tga",
	SWORD9 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\sword9.tga",

	SWORDOUT1 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\swordoutline1.tga",
	SWORDOUT2 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\swordoutline2.tga",
	SWORDOUT3 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\swordoutline3.tga",
	SWORDOUT4 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\swordoutline4.tga",
	SWORDOUT5 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\swordoutline5.tga",
	SWORDOUT6 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\swordoutline6.tga",
	SWORDOUT7 = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\icons\\role\\swordoutline7.tga",
}
