local mMT, M, F, E, P, L, MEDIA = unpack(ElvUI_mMediaTag)

mMT.options = {
	name = MEDIA.icon16 .. mMT.Name,
	handler = mMT,
	type = "group",
	--childGroups = "tab",
	args = {
		logo = {
			type = "description",
			name = "",
			order = 1,
			image = function()
				return "Interface\\Addons\\ElvUI_mMediaTag\\media\\logo", 512, 64
			end,
		},
		general = {
			order = 2,
			type = "group",
			name = L["General"],
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\general",
			childGroups = "tab",
			args = {},
		},
        unitframes = {
			order = 3,
			type = "group",
			name = L["Unitframes"],
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\unitframes",
			childGroups = "tab",
			args = {},
		},
        nameplates = {
			order = 4,
			type = "group",
			name = L["Nameplates"],
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\nameplates",
			childGroups = "tab",
			args = {},
		},
        datatexts = {
			order = 5,
			type = "group",
			name = L["Datatexts"],
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\datatexts",
			childGroups = "tab",
			args = {},
		},
        dock = {
			order = 6,
			type = "group",
			name = L["Dock"],
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\dock",
			childGroups = "tab",
			args = {},
		},
        tags = {
			order = 7,
			type = "group",
			name = L["TAGs"],
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\tags",
			childGroups = "tab",
			args = {},
		},
        misc = {
			order = 8,
			type = "group",
			name = L["Misc"],
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\misc",
			childGroups = "tab",
			args = {},
		},
        about = {
			order = 9,
			type = "group",
			name = MEDIA.color.green:WrapTextInColorCode(L["About"]),
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\about",
			childGroups = "tab",
			args = {},
		},
        license = {
			order = 10,
			type = "group",
			name = MEDIA.color.yellow:WrapTextInColorCode(L["License"] ),
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\license",
			childGroups = "tab",
			args = {},
		},
        changelog = {
			order = 11,
			type = "group",
			name = MEDIA.color.red:WrapTextInColorCode(L["Changelog"]),
			icon = "Interface\\Addons\\ElvUI_mMediaTag\\media\\options\\log",
			childGroups = "select",
			args = {},
		},
	},
}
