local mMT, DB, M, E, P, L, MEDIA = unpack(ElvUI_mMediaTag)

mMT.Changelog[414] = {
	DATE = "TBD",
	FIX = {
		"[DT-Combat-Time]: The combat timer threw an error on every frame when the icon for in or out of combat was set to None.",
		"[Tags]: The mMT-role tags threw an error on units without an assigned role, for example on your own frame while solo.",
		"[Tags]: The mMT-health:current tag used the short number format, it now uses the long one while mMT-health:current:short stays short.",
		"[Datatext]: The menus of the teleports, professions and game menu datatexts created new buttons every time they were opened, so the memory usage kept growing.",
		"[Datatext]: The menus of the teleports, professions and game menu datatexts now close when combat starts, an open teleports menu used to cause blocked action errors.",
		"[Portraits]: The test mode of the boss, arena and party frames threw an error with the Blizzard spec icon style.",
		"[DT-Score]: Your own keystone could throw an error when the game returned no color for its level.",
		"[System]: Mobs far above your level were saved as bosses for good and kept the boss classification on portraits and tags, the saved list is reset once.",
		"[DT-Teleports]: Teleports are used by their ID instead of their name, so items and toys that share a name no longer pick the wrong one.",
		"[System]: The changelog opened again after switching to another profile or character, it now only opens once per new version.",
		"[Localization]: 16 texts of the Objective Tracker options and the two latency lines of the game menu tooltip were shown in English in the German client.",
		"[DT-Teleports]: The highlight of the current dungeon was missing or marked the wrong dungeon after applying to several groups, after listing a new key right after a run and when your own group listed a dungeon.",
		"[Interrupt-On-CD]: Warlocks only get the kick marker and castbar color while the Felhunter or Felguard is out, Spell Lock and Axe Toss now follow the cooldown of the pet instead of a fixed spell per spec.",
		"[Interrupt-On-CD]: With a dead or missing warlock pet the castbar now shows the on CD color instead of ready.",
		"[Interrupt-On-CD]: Specs without their interrupt talent, for example Holy Paladins without Rebuke, no longer get castbars colored as ready.",
		"[Interrupt-On-CD]: The kick marker stayed visible when the interrupt came off cooldown during a cast.",
		"[Interrupt-On-CD]: Changed colors only applied after a reload, they now apply to the next cast.",
		"[Interrupt-On-CD]: Casts in dungeons could throw an error when the game hid whether they can be interrupted.",
		"[Important-Casts]: Casts of enemies in dungeons and raids could throw an error because their spell ID is hidden in Midnight.",
		"[Important-Casts]: The health bar color of a nameplate could be turned off again by a later cast in dungeons, it now stays until the unit dies or the nameplate shows a new unit.",
		"[Important-Casts]: Changing the border or health bar color turned off the demo mode.",
	},
	UPDATE = {
		"[DT-Combat-Time]: The combat timer updates its text once per second instead of on every frame.",
		"[DT-Game-Menu]: The memory and CPU tooltip only reads the CPU usage of the top five addons instead of every installed one.",
		"[System]: The portrait unit options and the color handling were rebuilt from shared templates, the options behave exactly as before but are easier to maintain.",
		"[Localization]: Spanish, Mexican Spanish, French, Italian, Brazilian Portuguese, Russian, Korean and Simplified and Traditional Chinese are complete again, around 285 missing texts per language were translated.",
		"[Localization]: Removed about 35 texts that were no longer used anywhere.",
		"[System]: Every build now runs automatic code checks (luacheck and StyLua) first, a cleanup pass removed unused code and brought all files to one formatting.",
		"[DT-Teleports]: The highlight of the current dungeon can be turned off and its color can be changed.",
		"[DT-Professions]: The colored profession icons were redrawn with simpler shapes and stronger contrast, so they stay sharp at small sizes in game.",
	},
	NEW = {
		"[DT-Teleports]: Optional highlight of the dungeon of your own keystone in the season list, with its own color.",
		"[Group-Keystones]: New window next to the group finder listing that shows the keystones of your group, the keys of other players need Details! or BigWigs.",
		"[Interrupt-On-CD]: Optional pixel glow around the castbar and/or health bar while a cast can be interrupted, optionally only for important casts and only when your interrupt is ready, with its own color.",
	},
}
