local mMT, DB, M, E, P, L, MEDIA = unpack(ElvUI_mMediaTag)

local textureDB = {
	textures = {
		blizz_round = {
			name = "Blizzard Round",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\extra_mask_mirror.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\corner.tga",
			flip = false,
			mirror = false,
		},
		blizz_round_up = {
			name = "Blizzard Round UP",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\texture_up.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\shadow_up.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\mask_up.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\mask_mirror_up.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\extra_mask_up.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\extra_mask_mirror_up.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round\\corner_up.tga",
			flip = false,
			mirror = false,
		},
		blizz_round_thick = {
			name = "Blizzard Round Thick",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\extra_mask_mirror.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\corner.tga",
			flip = false,
			mirror = false,
		},
		blizz_round_thick_up = {
			name = "Blizzard Round UP Thick",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\texture_up.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\shadow_up.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\mask_up.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\mask_mirror_up.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\extra_mask_up.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\extra_mask_mirror_up.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz round thick\\corner_up.tga",
			flip = false,
			mirror = false,
		},
		blizz_sharp = {
			name = "Blizzard Sharp",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\extra_mask_mirror.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\corner.tga",
			flip = false,
			mirror = false,
		},
		blizz_sharp_up = {
			name = "Blizzard Sharp UP",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\texture_up.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\shadow_up.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\mask_up.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\mask_mirror_up.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\extra_mask_up.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\extra_mask_mirror_up.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp\\corner_up.tga",
			flip = false,
			mirror = false,
		},
		blizz_sharp_thick = {
			name = "Blizzard Sharp Thick",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\extra_mask_mirror.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\corner.tga",
			flip = false,
			mirror = false,
		},
		blizz_sharp_thick_up = {
			name = "Blizzard Sharp UP Thick",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\texture_up.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\shadow_up.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\mask_up.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\mask_mirror_up.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\extra_mask_up.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\extra_mask_mirror_up.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\blizz sharp thick\\corner_up.tga",
			flip = false,
			mirror = false,
		},
		circle = {
			name = "Circle",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle\\extra_mask.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle\\embellishment.tga",
			disable_color = true,
			flip = false,
			mirror = false,
		},
		circle_thick = {
			name = "Circle Thick",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle thick\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle thick\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle thick\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle thick\\extra_mask.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\circle thick\\embellishment.tga",
			disable_color = true,
			flip = false,
			mirror = false,
		},
		cookie = {
			name = "Cookie",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\cookie\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\cookie\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\cookie\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\cookie\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\cookie\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\cookie\\extra_mask_mirror.tga",
			flip = false,
			mirror = false,
		},
		diamond = {
			name = "Diamond",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond\\extra_mask.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond\\embellishment.tga",
			disable_color = true,
			flip = false,
			mirror = false,
		},
		diamond_thick = {
			name = "Diamond Thick",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond thick\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond thick\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond thick\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond thick\\extra_mask.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\diamond thick\\embellishment.tga",
			disable_color = true,
			flip = false,
			mirror = false,
		},
		hexagon = {
			name = "Hexagon",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\hexagon\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\hexagon\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\hexagon\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\hexagon\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		leaf = {
			name = "Leaf",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\extra_mask_mirror.tga",
			flip = false,
			mirror = false,
		},
		leaf_mirror = {
			name = "Leaf Mirrored",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\texture_mirror.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\shadow_mirror.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\mask_mirror.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\extra_mask_mirror.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\leaf\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		octagon = {
			name = "Octagon",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\octagon\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\octagon\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\octagon\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\octagon\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		pad = {
			name = "Pad",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pad\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pad\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pad\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pad\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		parallelogram = {
			name = "Parallelogram",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\extra_mask_mirror.tga",
			flip = false,
			mirror = false,
		},
		parallelogram_mirror = {
			name = "Parallelogram Mirrored",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\texture_mirror.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\shadow_mirror.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\mask_mirror.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\extra_mask_mirror.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\parallelogram\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		pentagon = {
			name = "Pentagon",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pentagon\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pentagon\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pentagon\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pentagon\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pentagon\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\pentagon\\extra_mask_mirror.tga",
			flip = false,
			mirror = false,
		},
		shield = {
			name = "Shield",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\shield\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\shield\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\shield\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\shield\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		square = {
			name = "Square",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		square_thick = {
			name = "Square Thick",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square thick\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square thick\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square thick\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square thick\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		square_round = {
			name = "Square Round",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square round\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square round\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square round\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square round\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		square_round_thick = {
			name = "Square Round Thick",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square round thick\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square round thick\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square round thick\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\square round thick\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		tear = {
			name = "Tear",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\extra_mask_mirror.tga",
			flip = false,
			mirror = false,
		},
		tear_mirror = {
			name = "Tear Mirrored",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\texture_mirror.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\shadow_mirror.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\mask_mirror.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\extra_mask_mirror.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		tear_down = {
			name = "Tear down",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\texture_down.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\shadow_down.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\mask_down.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\mask_mirror_down.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\extra_mask_down.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\extra_mask_mirror_down.tga",
			flip = false,
			mirror = false,
		},
		tear_down_mirror = {
			name = "Tear down Mirrored",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\texture_mirror_down.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\shadow_mirror_down.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\mask_mirror_down.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\mask_down.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\extra_mask_mirror_down.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\tear\\extra_mask_down.tga",
			flip = false,
			mirror = false,
		},
		trapezoid = {
			name = "Trapezoid",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\mask.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\mask_mirror.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\extra_mask.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\extra_mask_mirror.tga",
			flip = false,
			mirror = false,
		},
		trapezoid_mirror = {
			name = "Trapezoid Mirrored",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\texture_mirror.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\shadow_mirror.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\mask_mirror.tga",
			mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\extra_mask_mirror.tga",
			extra_mask_mirror = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\trapezoid\\extra_mask.tga",
			flip = false,
			mirror = false,
		},
		rectangular = {
			name = "Rectangular",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\rectangular\\texture.tga",
			shadow = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\rectangular\\shadow.tga",
			mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\rectangular\\mask.tga",
			extra_mask = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\rectangular\\extra_mask.tga",
			embellishment = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\rectangular\\embellishment.tga",
			flip = false,
			mirror = false,
		},
	},
	extra = {
		blizz_boss = {
			name = "Blizzard Boss",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\blizz_boss.tga",
		},
		blizz_elite = {
			name = "Blizzard Elite",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\blizz_elite.tga",
		},
		blizz_rare = {
			name = "Blizzard Rare",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\blizz_rare.tga",
		},
		blizz_boss_neutral = {
			name = "Blizzard Boss Neutral",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\blizz_boss_neutral.tga",
		},
		blizz_rare_neutral = {
			name = "Blizzard Rare/ Elite Neutral",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\blizz_rare_neutral.tga",
		},
		round_monster = {
			name = "Round - Monster",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\round_monster.tga",
		},
		round_pulse = {
			name = "Round - Pulse",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\round_pulse.tga",
		},
		round_star = {
			name = "Round - Star",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\round_star.tga",
		},
		round_tech = {
			name = "Round - Tech",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\round_tech.tga",
		},
		round_zickzack = {
			name = "Round - Zickzack",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\round_zickzack.tga",
		},
		round_leaf = {
			name = "Round - Leaf",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\round_leaf.tga",
		},
		-- celestial = {
		-- 	name = "Celestial",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\celestial.tga",
		-- 	low = true,
		-- },
		-- dragon = {
		-- 	name = "Dragon",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\dragon.tga",
		-- },
		-- dragon_v2 = {
		-- 	name = "Dragon V2",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\dragon_v2.tga",
		-- },
		-- halocore = {
		-- 	name = "Halocore",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\halocore.tga",
		-- 	low = true,
		-- },
		-- leaf = {
		-- 	name = "Leaf",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\leaf.tga",
		-- },
		-- leaf_v2 = {
		-- 	name = "Leaf V2",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\leaf_v2.tga",
		-- },
		-- leaf_v3 = {
		-- 	name = "Leaf V3",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\leaf_v3.tga",
		-- },
		-- leaf_v4 = {
		-- 	name = "Leaf V4",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\leaf_v4.tga",
		-- },
		-- monument = {
		-- 	name = "Monument",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\monument.tga",
		-- 	low = true,
		-- },
		-- moondance = {
		-- 	name = "Moondance",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\moondance.tga",
		-- },
		-- spikes = {
		-- 	name = "Spikes",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\spikes.tga",
		-- },
		-- stars = {
		-- 	name = "Stars",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\stars.tga",
		-- },
		-- zickzack = {
		-- 	name = "Zickzack",
		-- 	texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\extra\\zickzack.tga",
		-- 	low = true,
		-- },
	},
	bg = {
		default = {
			name = "Default",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\bg\\bg_01.tga",
		},
		a = {
			name = "BG 1",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\bg\\bg_02.tga",
		},
		b = {
			name = "BG 2",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\bg\\bg_03.tga",
		},
		c = {
			name = "BG 3",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\bg\\bg_04.tga",
		},
		d = {
			name = "BG 4",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\bg\\bg_05.tga",
		},
		e = {
			name = "BG 5",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\bg\\bg_06.tga",
		},
		f = {
			name = "BG 6",
			texture = "Interface\\AddOns\\ElvUI_mMediaTag\\media\\portraits\\bg\\bg_07.tga",
		},
	},
}

MEDIA.portraits = textureDB
