local L = LibStub("AceLocale-3.0"):NewLocale("mMediaTag", "zhCN")
if not L then return end

L[" hidden at maximum level."] = true
L[" hidden in combat."] = true
L["!! Error - this is not an ID."] = true
L["AFK Logo"] = true
L["AFK Screen"] = true
L["AFK"] = true
L["Abbrev Name of Target."] = true
L["Abort"] = true
L["About"] = true
L["Absorbs color."] = true
L["Absorbs"] = true
L["Accepted"] = true
L["Active Output Audio Device"] = true
L["Actual reward:"] = true
L["Add XIV Background"] = true
L["Adds an Extra Icon to the Castbar."] = true
L["After setting the position, the interface must be reloaded once with /rl."] = true
L["All Dungeon Teleports"] = true
L["Alliance: "] = true
L["Allways withe"] = true
L["Alpha"] = true
L["Anchor Point"] = true
L["Anchor point for the extra Icon."] = true
L["Anchor"] = true
L["Apply"] = true
L["Arena"] = true
L["Attention! The path of the custom texture must comply with WoW standards. Example: Interface\\MYFOLDER\\MYFILE.tga. If you see a green box, the path is incorrect or you have a typo."] = true
L["Attributes"] = true
L["Auto Hover grow size"] = true
L["Auto Point"] = true
L["Auto Size"] = true
L["Auto color Border"] = true
L["Auto color Glow"] = true
L["Auto media color"] = true
L["Auto value"] = true
L["Auto"] = true
L["Available"] = true
L["BG Color"] = true
L["BOTTOM"] = true
L["Backdrop Texture"] = true
L["Background Color"] = true
L["Background Skin"] = true
L["Background Texture"] = true
L["Background color for Icons"] = true
L["Background color shift"] = true
L["Background"] = true
L["Bag - FREE"] = true
L["Bag - FREE/TOTAL"] = true
L["Bag - USED"] = true
L["Bags"] = true
L["Bar hight"] = true
L["Blizzard Targetunit role icon."] = true
L["Blizzard Unit role icon, only tank and healer."] = true
L["Blizzard Unit role icon."] = true
L["Border Color"] = true
L["Border and Glow"] = true
L["Border"] = true
L["Borders"] = true
L["Boss"] = true
L["CENTER"] = true
L["CIRCLE/ MOON"] = true
L["Calendar"] = true
L["Call To Arms"] = true
L["Cast Icon"] = true
L["Cast is out of range"] = true
L["Castbar Background Color"] = true
L["Castbar Color"] = true
L["Castbar Shield"] = true
L["Castbar Shield"] = true
L["Castbar Sound"] = true
L["Castbar Texture"] = true
L["Castbar"] = true
L["Center Text"] = true
L["Change Castbar Texture"] = true
L["Change Castbar color"] = true
L["Change Icons Colors"] = true
L["Change Log"] = true
L["Change Texture"] = true
L["Change the Castbar Texture."] = true
L["Change the Castbar color."] = true
L["Changelog"] = true
L["Changes the color of the castbar when the unit is out of range and interruptible."] = true
L["Character:"] = true
L["Chat Button"] = true
L["Chat Menu"] = true
L["Chest"] = true
L["Chromie"] = true
L["Circle"] = true
L["Circle"] = true
L["Class Colors"] = true
L["Class Icons Style"] = true
L["Class Icons"] = true
L["Class colored Background"] = true
L["Class colored Nameplates Border."] = true
L["Class colored Nameplates Glow."] = true
L["Class colored"] = true
L["Class"] = true
L["Clean Icons"] = true
L["Cleaned Memory"] = true
L["Click Color Style"] = true
L["Click left to open the main menu."] = true
L["Click to open Great Vault"] = true
L["Click to open LFD Frame"] = true
L["Left Click to roll"] = true
L["Collect Garbage"] = true
L["Collected"] = true
L["Color HC"] = true
L["Color Hover"] = true
L["Color Multiplier"] = true
L["Color Mythic"] = true
L["Color Mythic+"] = true
L["Color NHC"] = true
L["Color Normal"] = true
L["Color Settings"] = true
L["Color Style"] = true
L["Color Tip"] = true
L["Color Title"] = true
L["Color other"] = true
L["Color"] = true
L["Colored Menulist"] = true
L["Colored Text"] = true
L["Colors"] = true
L["Combat Icon and Time"] = true
L["Combat Time"] = true
L["Complete"] = true
L["Completed"] = true
L["Contact"] = true
L["Coords"] = true
L["Cosmetic Headerbar"] = true
L["Cosmetic"] = true
L["Creat mDock"] = true
L["Cross"] = true
L["Currency"] = true
L["Custom Alternative Power Texture"] = true
L["Custom Castbar Backdrop"] = true
L["Custom Castbar Texture"] = true
L["Custom Class colors"] = true
L["Custom Docks"] = true
L["Custom Font Size"] = true
L["Custom Font color"] = true
L["Custom Health Backdrop"] = true
L["Custom Health Texture"] = true
L["Custom Icon Color"] = true
L["Custom NPC ID"] = true
L["Custom Notification Color"] = true
L["Custom Portrait Textures"] = true
L["Custom Power Backdrop"] = true
L["Custom Power Texture"] = true
L["Custom Texture DD"] = true
L["Custom Texture Heal"] = true
L["Custom Texture Tank"] = true
L["Custom Textures"] = true
L["Custom Unitframe Backgrounds"] = true
L["Custom Unitframe Textures"] = true
L["Custom click Color"] = true
L["Custom color for Datatext Tip"] = true
L["Custom color"] = true
L["Custom hover Color"] = true
L["Custom"] = true
L["DD"] = true
L["DEATHKNIGHT"] = true
L["DEMONHUNTER"] = true
L["DEV ICON"] = true
L["DEV Tools"] = true
L["DF Dungeons"] = true
L["DND"] = true
L["DRUID"] = true
L["Dark Class"] = true
L["DataTexts"] = true
L["Datapanels"] = true
L["Datatext Colors"] = true
L["Datatext Options Color (Tooltip)"] = true
L["Datatext Settings"] = true
L["Date Style"] = true
L["Dead"] = true
L["Death Counter color."] = true
L["Death Counter, resets in new Instances."] = true
L["Death"] = true
L["Deaths"] = true
L["Default Castbar Texture"] = true
L["Default Font"] = true
L["Default"] = true
L["Deficit:"] = true
L["Delay time"] = true
L["Delete ID"] = true
L["Delete NPC ID"] = true
L["Delete all Settings"] = true
L["Delete all and reset the list."] = true
L["Delete all"] = true
L["Delete filter"] = true
L["Delete the Spell, enter a ID."] = true
L["Description"] = true
L["Diamond"] = true
L["Difficulties Colors"] = true
L["Difficulty Text"] = true
L["Disable All"] = true
L["Disable"] = true
L["Display the instance name instead of Datatext name. Uses the same format as InstanceDifficulty."] = true
L["Displays Power/Mana for Heal only, in combat."] = true
L["Displays Power/Mana, in combat."] = true
L["Displays Power/Mana, with a low healer warning, hidden when full."] = true
L["Displays Power/Mana, with a low healer warning."] = true
L["Displays a ! if the Unit is a Quest NPC."] = true
L["Displays an icon when the unit is flagged for PvP."] = true
L["Displays the AFK Status."] = true
L["Displays the Death counter only when the unit is Death and Shows a Text (Death: 7), resets in new instances."] = true
L["Displays the Death counter only when the unit is Death, resets in new instances."] = true
L["Displays the Faction Icon."] = true
L["Displays the Faction."] = true
L["Displays the Unit AFK Status."] = true
L["Displays the Unit Class Icon only for Rare and Boss NPCs."] = true
L["Displays the Unit Class Icon only for Rare and Rare Elite NPCs."] = true
L["Displays the Unit Class Icon, only for Boss NPCs."] = true
L["Displays the Unit Class Icon."] = true
L["Displays the Unit Class."] = true
L["Displays the Unit Status Icon."] = true
L["Displays the Unit Status text and time."] = true
L["Displays the Unit Status."] = true
L["Displays the healer's Power/Mana, with a low healer warning, hidden when full."] = true
L["Displays the healer's Power/Mana, with a low healer warning."] = true
L["Displays the icons for the professions in the menu."] = true
L["Displays the icons of the menu list."] = true
L["Displays the last word of the Unit name, only in an Instance."] = true
L["Displays the last word of the Unit name."] = true
L["Displays the opposite Faction Icon."] = true
L["Displays the opposite Faction."] = true
L["Displays the unit's current health as a percentage with absorb values"] = true
L["Dock on Top"] = true
L["Dock"] = true
L["Drop flipped"] = true
L["Drop round flipped"] = true
L["Drop round"] = true
L["Drop"] = true
L["Dungeon Name"] = true
L["Dungeon Skin"] = true
L["Dungeon"] = true
L["Durability and Item Level"] = true
L["Durability"] = true
L["Durability/ Ilevel"] = true
L["ELITE"] = true
L["ENEMY"] = true
L["ERROR! Please open the Mythic+ window, LFG Tool or Reload UI!"] = true
L["EVOKER"] = true
L["Earned:"] = true
L["Elite"] = true
L["ElvUI Background Color"] = true
L["ElvUI media color"] = true
L["Enable Arena Portraits"] = true
L["Enable Borders"] = true
L["Enable Boss Portraits"] = true
L["Enable Cast Icons"] = true
L["Enable Class colored Background"] = true
L["Enable Corner"] = true
L["Enable Custom Alternative Power Texture"] = true
L["Enable Custom Castbar Backdrop"] = true
L["Enable Custom Castbar Texture"] = true
L["Enable Custom Health Backdrop"] = true
L["Enable Custom Health Texture"] = true
L["Enable Custom Power Backdrop"] = true
L["Enable Custom Power Texture"] = true
L["Enable Custom Textures"] = true
L["Enable Filter"] = true
L["Enable Focus Portraits"] = true
L["Enable Gradient colors, this will use the second color."] = true
L["Enable Important Spells module."] = true
L["Enable Important Spells"] = true
L["Enable Inner Shadow"] = true
L["Enable Interrupt on CD colors for Castbar"] = true
L["Enable Nameplate Execute Marker"] = true
L["Enable Nameplate Health Marker"] = true
L["Enable ObjectiveTracker Skin."] = true
L["Enable Party Portraits"] = true
L["Enable Pet Portraits"] = true
L["Enable Player Portraits"] = true
L["Enable Portraits"] = true
L["Enable Rare/Elite Border"] = true
L["Enable Shadow"] = true
L["Enable Target Portraits"] = true
L["Enable Target of Target Portraits"] = true
L["Enable custom colors"] = true
L["Enable not Interruptible Shield"] = true
L["Enable on Nameplates"] = true
L["Enable on Unitframes"] = true
L["Enable the custom role icons"] = true
L["Enable the custom textures"] = true
L["Enable this Filter."] = true
L["Enable this module on Nameplates."] = true
L["Enable this module on Unitframes."] = true
L["Enable"] = true
L["Enables or disables Quest Icon"] = true
L["Enables or disables Tooltip Icon"] = true
L["Engineering"] = true
L["Enhancements"] = true
L["Enter a NPC ID"] = true
L["Enter a Spell ID it accepts only Numbers."] = true
L["Enter a name for your filter."] = true
L["Error decompressing data."] = true
L["Error deserializing:"] = true
L["Error importing profile. String is invalid or corrupted!"] = true
L["Example"] = true
L["Execute Marker"] = true
L["Execute markers"] = true
L["Execute value HP%"] = true
L["Execute value based on your Class"] = true
L["Explanation"] = true
L["Export"] = true
L["Extra Icon Anchor"] = true
L["FRIENDLY"] = true
L["Failed"] = true
L["Filter Name"] = true
L["First and Second Profession"] = true
L["Fix:"] = true
L["Focus"] = true
L["Font Settings"] = true
L["Font Size"] = true
L["Font contour"] = true
L["Font"] = true
L["Force reaction color"] = true
L["Forces reaction color for all Units."]  = true
L["Frame Level"] = true
L["Frame Strata"] = true
L["Friends List"] = true
L["Friends"] = true
L["GOLD"] = true
L["Game Menu"] = true
L["General"] = true
L["GetCurrenciesInfo no Table or no ID."] = true
L["Ghost"] = true
L["Gradient  Mode"] = true
L["Gradient Orientation"] = true
L["Gradient"] = true
L["Grays"] = true
L["Great Vault"] = true
L["Guild Group"] = true
L["Guild"] = true
L["HUNTER"] = true
L["Header"] = true
L["Healer"] = true
L["Health changes between maximum Health and Current Health - Percent in combat with absorb values."] = true
L["Health changes between maximum Health and Current Health - Percent in combat."] = true
L["Health changes between maximum Health and Percent in combat, with Status Icons."] = true
L["Health changes between maximum Health and Percent in combat, without AFK Status."] = true
L["Health changes between maximum Health and Percent in combat. Without Death Status."] = true
L["Health changes between maximum Health and Percent in combat."] = true
L["Health"] = true
L["Healthmarker"] = true
L["Healthmarkers"] = true
L["Help"] = true
L["Here you can enable or disable individual texture packs to speed up the loading of the dropdown menu. Sometimes it may be necessary to do a /rl after enabling or disabling the packs."] = true
L["Here you can set the color of the castbar when your own interrupt spell is on CD or will be ready."] = true
L["Hide (All Objectives)"] = true
L["Hide Dash"] = true
L["Hide Text"] = true
L["Hide Timer in Seconds"] = true
L["Hide if Zero"] = true
L["Highlight Color"] = true
L["Highlight dim Value"] = true
L["Highlight my Keystone"] = true
L["Home Latency:"] = true
L["Horde: "] = true
L["Hover Color Style"] = true
L["Hover Custom Color"] = true
L["Hover grow size"] = true
L["ID list"] = true
L["IDs"] = true
L["Icon Anchor"] = true
L["Icon Settings"] = true
L["Icon Size"] = true
L["Icon and Name"] = true
L["Icon color. Note: If you chose a colored icon, set the color to white for the best look."] = true
L["Icon flash"] = true
L["Icon in Combat"] = true
L["Icon offset if not Auto point is enabled."] = true
L["Icon out of Combat"] = true
L["Icon seize if not Auto size is enabled."] = true
L["Icon"] = true
L["Icons"] = true
L["Import"] = true
L["Import/ Export of Spell IDs"] = true
L["Import/ Export of this Settings"] = true
L["Important Spells"] = true
L["Important:"] = true
L["In Classic, the docks may look different, since not all modules are available in this version. You can customize the docks in the settings of ElvUI."] = true
L["Indicator Color"] = true
L["Info Screen"] = true
L["Info! To achieve an optimal result with the portraits, a texture should be set for the texture, border and mask.\nThe mask is always required and no portrait will be visible without it.\n\n"] = true
L["Inner Shadow Color"] = true
L["Inner Shadow"] = true
L["Instance Difficulty"] = true
L["Instance Name"] = true
L["Interrupt in time color"] = true
L["Interrupt on CD Settings"] = true
L["Interrupt on CD"] = true
L["Interrupt on cd color"] = true
L["Interrupt out of range color"] = true
L["Itemlevel"] = true
L["Keystone to Chat"] = true
L["Keystone"] = true
L["Keystones in your Group"] = true
L["Keystones on your Account"] = true
L["LEFT"] = true
L["Level ??"] = true
L["Level Colors"] = true
L["Level changes to resting in resting Areas."] = true
L["Level"] = true
L["Level: "] = true
L["License"] = true
L["Load All"] = true
L["Load Pack"] = true
L["Load only in Instance"] = true
L["Loadouts"] = true
L["Location"] = true
L["Logo Texture"] = true
L["M+ Keystone Level"] = true
L["M+ Score"] = true
L["M+ Season"] = true
L["M+ Time"] = true
L["MAGE"] = true
L["MONK"] = true
L["MaUI XIV Like"] = true
L["Main Professions"] = true
L["Main color."] = true
L["Marker Settings"] = true
L["Mask"] = true
L["Middle click to open M+ Frame"] = true
L["Mirrored Mask"]  = true
L["Misc"] = true
L["Missing"] = true
L["Mobile"] = true
L["Moon"] = true
L["Moon"] = true
L["Mounts"] = true
L["Mythic Plus Keystone"] = true
L["Mythic+ Colors"] = true
L["Mythic+ Score"] = true
L["NEUTRAL"] = true
L["NPC IDS"] = true
L["Name"] = true
L["Nameplates"] = true
L["New:"] = true
L["No Dungeon"] = true
L["No Keystone"] = true
L["No Main Professions"] = true
L["No Professions"] = true
L["No Score"] = true
L["No Secondary Professions"] = true
L["No Texture found"] = true
L["No decimal values for percentage."] = true
L["No professions available!"] = true
L["None"] = true
L["Normal Color Style"] = true
L["Not Ready"] = true
L["Notification Color Style"] = true
L["Notification"] = true
L["Objective Tracker"] = true
L["Offline"] = true
L["Offset"] = true
L["Only if Target"] = true
L["Open Settings"] = true
L["Optimal size for the logo is 512 x 128 Pixel"] = true
L["Other Colors"] = true
L["Other Colors"] = true
L["Other"] = true
L["Others"] = true
L["Output Audio Device"] = true
L["Output/ Input"] = true
L["Overall Score"] = true
L["Overlay Color"] = true
L["Overlay Texture"] = true
L["PALADIN"] = true
L["PRIEST"] = true
L["Pad"] = true
L["Panels"] = true
L["Party"] = true
L["Pet"] = true
L["Pets"] = true
L["Phase Icon"] = true
L["Phase"] = true
L["Phasing"] = true
L["Play a Sound"] = true
L["Player"] = true
L["Plays a Sound."] = true
L["Plays a sound only when the unit is your target."] = true
L["Portrait Offset/ Zoom"] = true
L["Portraits"] = true
L["Position Settings"] = true
L["Power"] = true
L["Preview"] = true
L["Professions"] = true
L["Profit:"] = true
L["Progress Bar"] = true
L["Progress Bars"] = true
L["Progress Good"] = true
L["Progress Transit"] = true
L["Progress bad"] = true
L["Progress"] = true
L["Quest Count"] = true
L["Quest Icons"] = true
L["RARE ELITE"] = true
L["RARE"] = true
L["RIGHT"] = true
L["ROGUE"] = true
L["Rare & Elite - Border"] = true
L["Rare & Elite - Shadow"] = true
L["Rare & Elite"]  = true
L["Rare Border Color"] = true
L["Rare Elite"] = true
L["Rare"] = true
L["Ready Check Icons"] = true
L["Ready Check"] = true
L["Ready"] = true
L["Readymarker color"] = true
L["Rejected"] = true
L["Release"] = true
L["ReloadUI"] = true
L["Replace the Unit name with Status Icon, if applicable."] = true
L["Replace the Unit name with Status, if applicable."] = true
L["Reset Character Data: Hold Shift + Right Click"] = true
L["Reset DB"] = true
L["Reset Session Data: Hold Ctrl + Right Click"] = true
L["Reset"] = true
L["Resurrection"] = true
L["Right click to open the ElvUI settings."] = true
L["Role Colors"] = true
L["Role Icons"] = true
L["Roll Button"] = true
L["SHAMAN"] = true
L["Same as"] = true
L["Season has not started yet."] = true
L["Secondary Professions"] = true
L["Select Volume Stream"] = true
L["Select a filter to delete."] = true
L["Select an Icon."] = true
L["Select the filter to edit."] = true
L["Send Keystone to Chat with !keys command"] = true
L["Server: "] = true
L["Session:"] = true
L["Set the icon size according to the height of the castbar."] = true
L["Sets the offset according to the anchor."] = true
L["Settings"] = true
L["Shadow Color"] = true
L["Shadow"] = true
L["Shadow/ Border"] = true
L["Sharding"] = true
L["Short Number"] = true
L["Shortened version of abbrev Name of Target."] = true
L["Shortened version of"] = true
L["Show Datatext Icon"] = true
L["Show Great Vault infos in the Tooltip and opens the Great Vault"] = true
L["Show Groupmember Keys."] = true
L["Show Icon"] = true
L["Show Icons"] = true
L["Show Quest Level"] = true
L["Show Max Count"] = true
L["Show Role if in Group"] = true
L["Show Text on Icon"] = true
L["Show Text"] = true
L["Show Welcome text"] = true
L["Show Year"] = true
L["Show amount in Bag"] = true
L["Show only Quests on Map"] = true
L["Show weekly upgrades"] = true
L["Shows Name"] = true
L["Shows a marker on the castbar when the interrupt spell will be ready."] = true
L["Shows the Healthmarkers only in a Instance"] = true
L["Shows the Weekly Affixes."] = true
L["Shows your Keystone in the tooltip."] = true
L["Simple Square"] = true
L["Simple"] = true
L["Size"] = true
L["Skin"] = true
L["Skull"] = true
L["Smart Level changes to resting in resting Areas."] = true
L["Some settings have been changed! For mMediaTag to work properly, a reload of the interface is recommended. Should a reload be performed now?"] = true
L["Sort Methods"] = true
L["Sort"] = true
L["Sound"] = true
L["Spell Filters"] = true
L["Spell Settings"] = true
L["Spell id"] = true
L["Spent:"] = true
L["Square"] = true
L["Square"] = true
L["Star"] = true
L["Status Colors"] = true
L["Status Icons"] = true
L["Status"] = true
L["Style"] = true
L["Summon Icons"] = true
L["Summon"] = true
L["TOP"] = true
L["Tags"] = true
L["Talent Builds"] = true
L["Tank and Healer roles as text."] = true
L["Tank"] = true
L["Target counter (Party and Raid)."] = true
L["Target counter Icon (Flat Circle)."] = true
L["Target counter Icon (Flat Diamond)."] = true
L["Target counter Icon (Flat Square)."] = true
L["Target counter Icon (Flat Stop shield)."] = true
L["Target counter Icon (Glas Circle)."] = true
L["Target counter Icon (Roleicons)."] = true
L["Target of Target"] = true
L["Target"] = true
L["Targetmarker Icons"] = true
L["Targetunit colors with mMediaTag colors for Rare, Rareelite, Elite and Boss and Classcolors."] = true
L["Targetunit role icon."] = true
L["Teleports"] = true
L["Text to Instance Name"] = true
L["Text to display"] = true
L["Text"] = true
L["Texture Form"] = true
L["Texture Packs"] = true
L["Texture Style"] = true
L["Texture"] = true
L["Textures"] = true
L["Thanks to:"] = true
L["The ImportantSpells IDs and Settings have been reset to reflect the latest updates in mMT."] = true
L["The ObjectiveTracker settings have been reset to reflect the latest updates in mMT."] = true
L["The default castbar texture when no spell modification is active."] = true
L["The position settings of Instance Difficulty are controlled by ElvUI in Maps, Minimap, Instance Difficulty."] = true
L["These are just examples of how to create your own dock with ElvUI's custom bars.\n\n\nTo create your own bar you have to go to ElvUI under ElvUI>Datatext>Bars Steps 1. enter name press OK and click Add, set the width of the bar depends on how many icons you want to display, the height of the bar is also the size of the icons. Set the number of data text and now you only need to assign the icons to the places, for example 1 = Dock FPS, 2 = Dock Profession and so on.\n\n"] = true
L["Thin"] = true
L["This Week Affix"] = true
L["This is the Border texture for the Rare & Elite texture."] = true
L["This is the Border texture for the portraits."] = true
L["This is the Mask texture for the portraits. This texture is used to cut out the portrait of the Unit."] = true
L["This is the Rare & Elite texture for the portraits."] = true
L["This is the gradient color and will only be used if the Gradient mod is enabled."] = true
L["This is the inner shadow texture for the portraits."] = true
L["This is the main texture for the portraits."] = true
L["This is the mirrored Mask texture for the portraits. This texture is used to cut out the portrait of the Unit."] = true
L["This is the shadow texture for the Rare & Elite texture."] = true
L["This is the shadow texture for the portraits."] = true
L["This will automatically change the ElvUI Media color to your class color."] = true
L["Time until the text disappears"] = true
L["Title"] = true
L["Toggle Volume Stream"] = true
L["ToolTip anchor on cursor"] = true
L["Tooltip Icon size."] = true
L["Tooltip Icon"] = true
L["Tooltip Keystone"] = true
L["Tooltip"] = true
L["Total: "] = true
L["Toys"] = true
L["Tracked Achievements"] = true
L["Triangle"] = true
L["Trigger "] = true
L["Trigger"] = true
L["Unit colors with mMediaTag colors for Rare and Rareelite."] = true
L["Unit colors with mMediaTag colors for Rare, Rareelite, Elite and Boss and Classcolors."] = true
L["Unit role icon, only tank and healer."] = true
L["Unit role icon."] = true
L["Unit"] = true
L["Unitframe Icons"] = true
L["Update:"] = true
L["Upgrade Icon"] = true
L["Upgrade"] = true
L["Use Class Icons"] = true
L["Use Default NPC IDs"] = true
L["Use Eltruism colors"] = true
L["Use MerathilisUI colors"] = true
L["Use only Default Color"] = true
L["Uses Custom and default NPC IDs"] = true
L["Uses for every Unit the Default Color."] = true
L["Values"] = true
L["Version:"] = true
L["Volume Streams"] = true
L["Volume"] = true
L["WARLOCK"] = true
L["WARRIOR"] = true
L["Waiting"] = true
L["Warmode"] = true
L["Weekly Affix"] = true
L["Weekly Affixes"] = true
L["Weekly Score"] = true
L["Welcome text"] = true
L["Welcome to %s %s version |CFFF7DC6F%s|r, type |CFF58D68D/mmt|r to access the in-game configuration menu."] = true
L["White"] = true
L["WoW Token:"] = true
L["World Latency:"] = true
L["X offset"] = true
L["X-Icon Size"] = true
L["X-Position"] = true
L["Y offset"] = true
L["Y-Icon Size"] = true
L["Y-Position"] = true
L["You are trying to load an outdated profile, unfortunately this is not possible."] = true
L["Zone"] = true
L["Zooms the texture so we get clean icons without borders."] = true
L["Zzz"] = true
L["and"] = true
L["do not show when the interrupt spell is ready in X seconds."] = true
L["first Profession"] = true
L["left click to open LFD Window"] = true
L["left click to open the menu."] = true
L["left click to open the small menu."] = true
L["mMT Dock"] = true
L["mMT Extra"] = true
L["mMT Raidtarget marker Icons"] = true
L["mMT XIV Like Color"] = true
L["mMT XIV Like"] = true
L["middle click to open the Dungeon Teleports menu."] = true
L["no Status version of"] = true
L["right click to open Great Vault Window"] = true
L["right click to open LFD Window"] = true
L["right click to open the other Teleports menu."] = true
L["second Profession"] = true
L["white Text"] = true
L["white Value"] = true
L["white shield Icon"] = true
L["|cFFffffffLeft Click:|r Select Volume Stream"] = true
L["|cFFffffffMiddle Click:|r Toggle Mute Master Stream"] = true
L["|cFFffffffRight Click:|r Toggle Volume Stream"] = true
L["|cFFffffffShift + Left Click:|r Open System Audio Panel"] = true
L["|cFFffffffShift + Right Click:|r Select Output Audio Device"] = true
L["|cffFFFFFFControl + Left Click:|r Change Loadout"] = true
L["|cffFFFFFFLeft Click:|r Change Talent Specialization"] = true
L["|cffFFFFFFRight Click:|r Change Loot Specialization"] = true
L["|cffFFFFFFShift + Left Click:|r Show Talent Specialization UI"] = true

-- new
L["Released"] = true
L["Version"] = true
L["Important"] = true
L["New"] = true
L["Updates"] = true
L["Fixes"] = true
L["Left Click"] = true
L["Right Click"] = true
L["Info: The Skin can be affected by other addons if they add a skin for all windows. To fix the problem, the skin must be deactivated in the other addon. This is not a bug of mMT."] = true
