local L = ElvUI[1].Libs.ACL:NewLocale("ElvUI", "zhTW")
if not L then return end

L[" hidden at maximum level."] = true
L["%s: |CFFE74C3CNo professions available!|r"] = true
L["%sActual reward:|r"] = "%sAktuelle Belohnung:|r";
L["%sERROR! Please open the Mythic+ window, LFG Tool or Reload UI!|r"] = true
L["%sM|r%s+%s|r"] = true
L["0 = disable"] = true
L["AFK Screen"] = true
L["AFK"] = true
L["Abbrev Name of Target."] = true
L["Abort"] = true
L["About"] = true
L["Accepted"] = true
L["Active Output Audio Device"] = true
L["Add XIV Background"] = true
L["After setting the position, the interface must be reloaded once with /rl."] = true
L["All Dungeon Teleports"] = true
L["Alliance: "] = true
L["Allways withe"] = true
L["Alpha"] = "Alpha";
L["Anchor Point"] = true
L["Apply"] = true
L["Arena"] = true
L["Attention! The path of the custom texture must comply with WoW standards. Example: Interface\\MYFOLDER\\MYFILE.tga. If you see only a green box, the path is not correct or there is a typo."] = true
L["Attributes"] = true
L["Auto Hover grow size"] = true
L["Auto Size"] = true
L["Auto color Border"] = true
L["Auto color Glow"] = true
L["Auto range"] = true
L["Auto"] = true
L["Available"] = true
L["BG Color"] = true
L["Background Color"] = true
L["Background color for Icons"] = true
L["Background"] = true
L["Bag - FREE"] = true
L["Bag - FREE/TOTAL"] = true
L["Bag - USED"] = true
L["Bags"] = true
L["Blizzard Targetunit role icon."] = true
L["Blizzard Unit role icon."] = true
L["Border Color"] = true
L["Border and Glow"] = true
L["Border"] = true
L["Boss"] = true
L["Calendar"] = true
L["Call To Arms"] = true
L["Castbar BG Color"] = true
L["Castbar Shield"] = true
L["Castbar"] = true
L["Center Text"] = true
L["Change Icons Colors"] = true
L["Change Log"] = true
L["Change Texture"] = true
L["Changelog"] = true
L["Character: "] = true
L["Chat Button"] = true
L["Chat Menu"] = true
L["Chat"] = true
L["Chromie"] = true
L["Circle"] = true
L["Class Colors"] = true
L["Class Icons"] = true
L["Class colored Nameplates Border."] = true
L["Class colored Nameplates Glow."] = true
L["Class"] = true
L["Clean Icons"] = true
L["Cleaned Memory"] = true
L["Click Color Style"] = true
L["Click left to open the main menu."] = true
L["Click to open Great Vault"] = true
L["Click to open LFD Frame"] = true
L["Click to roll 1-100"] = true
L["Collect Garbage"] = true
L["Collected"] = true
L["Color A"] = true
L["Color B"] = true
L["Color HC"] = true
L["Color Hover"] = true
L["Color Multiplier"] = true
L["Color Mythic"] = true
L["Color Mythic+"] = true
L["Color NHC"] = true
L["Color Normal"] = true
L["Color Settings"] = true
L["Color Style"] = true
L["Color Tip"] = true
L["Color Title"] = true
L["Color other"] = true
L["Color"] = true
L["Colored Menulist"] = true
L["Colored Text"] = true
L["Colors"] = true
L["Combat Icon and Time"] = true
L["Completed"] = true
L["Contact"] = true
L["Coords"] = true
L["Cosmetic Headerbar"] = true
L["Cosmetic"] = true
L["Creat mDock"] = true
L["Cross"] = true
L["Currency"] = true
L["Custom Castbar Backdrop"] = true
L["Custom Class colors"] = true
L["Custom Font Size"] = true
L["Custom Font color"] = true
L["Custom Health Backdrop"] = true
L["Custom Icon Color"] = true
L["Custom NPCID"] = true
L["Custom Notification Color"] = true
L["Custom Power Backdrop"] = true
L["Custom Texture DD"] = true
L["Custom Texture Heal"] = true
L["Custom Texture Tank"] = true
L["Custom Textures"] = true
L["Custom Unitframe Backgrounds"] = true
L["Custom click Color"] = true
L["Custom color for Datatext Tip"] = true
L["Custom color"] = true
L["Custom hover Color"] = true
L["Custom"] = true
L["DEATHKNIGHT"] = true
L["DEMONHUNTER"] = true
L["DEV ICON"] = true
L["DEV Tools"] = true
L["DF Dungeons"] = true
L["DND"] = true
L["DRUID"] = true
L["Dark Class"] = true
L["DataTexts"] = true
L["Datapanels"] = true
L["Datatext Colors"] = true
L["Datatext Options Color (Tooltip)"] = true
L["Date Style"] = true
L["Dead"] = true
L["Death Counter color."] = true
L["Death Counter, resets in new Instances."] = true
L["Death"] = true
L["Deaths"] = true
L["Default Font"] = true
L["Default"] = true
L["Deficit:"] = true
L["Delete NPCID"] = true
L["Delete all Settings"] = true
L["Delete all"] = true
L["Description"] = true
L["Diamond"] = true
L["Difficulties Colors"] = true
L["Difficulty Text"] = true
L["Disable All"] = true
L["Disable"] = true
L["Displays Power/Mana for Heal only, in combat."] = true
L["Displays Power/Mana, in combat."] = true
L["Displays Power/Mana, with a low healer warning, hidden when full."] = true
L["Displays Power/Mana, with a low healer warning."] = true
L["Displays a ! if the Unit is a Quest NPC."] = true
L["Displays an icon when the unit is flagged for PvP."] = true
L["Displays the Death counter only when the unit is Death and Shows a Text (Death: 7), resets in new instances."] = true
L["Displays the Death counter only when the unit is Death, resets in new instances."] = true
L["Displays the Faction Icon."] = true
L["Displays the Faction."] = true
L["Displays the Unit AFK Status."] = true
L["Displays the Unit Class Icon only for Boss NPCs."] = true
L["Displays the Unit Class Icon only for Rare and Boss NPCs."] = true
L["Displays the Unit Class Icon only for Rare and Rare Elite NPCs."] = true
L["Displays the Unit Class Icon."] = true
L["Displays the Unit Class."] = true
L["Displays the Unit Status Icon."] = true
L["Displays the Unit Status text and time."] = true
L["Displays the Unit Status."] = true
L["Displays the healer's Power/Mana, with a low healer warning, hidden when full."] = true
L["Displays the healer's Power/Mana, with a low healer warning."] = true
L["Displays the icons for the professions in the menu."] = true
L["Displays the last word of the Unit name, only in an Instance."] = true
L["Displays the last word of the Unit name."] = true
L["Displays the opposite Faction Icon."] = true
L["Displays the opposite Faction."] = true
L["Dock on Top"] = true
L["Dock"] = true
L["Dungeon Name"] = true
L["Dungeon"] = true
L["Durability and Item Level"] = true
L["Durability"] = true
L["Durability/ Ilevel"] = true
L["ENEMY"] = true
L["ERROR! Please open the Mythic+ window, LFG Tool or Reload UI!"] = true
L["EVOKER"] = true
L["Earned:"] = true
L["Elite"] = true
L["Enable Arena Portraits"] = true
L["Enable Borders"] = true
L["Enable Boss Portraits"] = true
L["Enable Corner"] = true
L["Enable Custom Castbar Backdrop"] = true
L["Enable Custom Health Backdrop"] = true
L["Enable Custom Power Backdrop"] = true
L["Enable Focus Portraits"] = true
L["Enable Inner Shadow"] = true
L["Enable Nameplate Execute indicator"] = true
L["Enable Nameplate Healthmarker"] = true
L["Enable Party Portraits"] = true
L["Enable Pet Portraits"] = true
L["Enable Player Portraits"] = true
L["Enable Portraits"] = true
L["Enable Rare/Elite Border"] = true
L["Enable Shadow"] = true
L["Enable Target Portraits"] = true
L["Enable Target of Target Portraits"] = true
L["Enable custom colors"] = true
L["Enable the Microbar Skins"] = true
L["Enable"] = true
L["Enables or disables Quest Icon"] = true
L["Engineering"] = true
L["Enhancements"] = true
L["Enter a NPCID"] = true
L["Error decompressing data."] = true
L["Error deserializing:"] = true
L["Error importing profile. String is invalid or corrupted!"] = true
L["Example"] = true
L["Execute Marker"] = true
L["Execute Range HP%"] = true
L["Execute markers"] = true
L["Execute range based on your Class"] = true
L["Explanation"] = true
L["Export"] = true
L["FPS / MS"] = true
L["FPS"] = true
L["FPS/ MS"] = true
L["FPS/MS"] = true
L["FPS:"] = true
L["FRIENDLY"] = true
L["Fix:"] = true
L["Focus"] = true
L["Font Size"] = true
L["Font contour"] = true
L["Font"] = true
L["Frame Level"] = true
L["Frame Strata"] = true
L["Friends List"] = true
L["Friends"] = true
L["GOLD"] = true
L["Game Menu"] = true
L["General"] = true
L["GetCurrenciesInfo no Table or no ID."] = true
L["Ghost"] = true
L["Git"] = true
L["Gradient Orientation"] = true
L["Gradient"] = true
L["Grays"] = true
L["Great Vault"] = true
L["Guild Group"] = true
L["Guild"] = true
L["H"] = true
L["HUNTER"] = true
L["Heal"] = true
L["Health changes between maximum Health and Current Health - Percent in combat."] = true
L["Health changes between maximum Health and Percent in combat, with Status Icons."] = true
L["Health changes between maximum Health and Percent in combat, without AFK Status."] = true
L["Health changes between maximum Health and Percent in combat."] = true
L["Health markers"] = true
L["Health"] = true
L["Healthmarker 1"] = true
L["Healthmarker 2"] = true
L["Healthmarker 3"] = true
L["Healthmarker 4"] = true
L["Help"] = true
L["Here you can enable or disable individual texture packs to speed up the loading of the dropdown menu. Sometimes it may be necessary to do a /rl after enabling or disabling the packs."] = true
L["Hide Dash"] = true
L["Hide Text"] = true
L["Hide Timer in Seconds"] = true
L["Hide if Zero"] = true
L["Highlight my Keystone"] = true
L["Home Latency:"] = true
L["Horde: "] = true
L["Hover Color Style"] = true
L["Hover Custom Color"] = true
L["Hover grow size"] = true
L["IDs"] = true
L["Icon Settings"] = true
L["Icon and Name"] = true
L["Icon flash"] = true
L["Icon in Combat"] = true
L["Icon out of Combat"] = true
L["Icon size"] = true
L["Icon"] = true
L["Icons"] = true
L["If the unit is alive, its health will change between maximum health and percentage in combat."] = true
L["Import"] = true
L["Import/ Export of this Settings"] = true
L["Important Spells"] = true
L["Important:"] = true
L["In Classic, the docks may look different, since not all modules are available in this version. You can customize the docks in the settings of ElvUI."] = true
L["Indicator Color"] = true
L["Info Screen"] = true
L["Inner Shadow Color"] = true
L["Inner Shadow"] = true
L["Instance Difficulty"] = true
L["Instance Name"] = true
L["Interrupt on CD"] = true
L["Item"] = true
L["Itemlevel"] = true
L["Keystone to Chat"] = true
L["Keystone"] = true
L["Keystones in your Group"] = true
L["Keystones on your Account"] = true
L["Level ??"] = true
L["Level Colors"] = true
L["Level changes to resting in resting Areas."] = true
L["Level"] = true
L["Licens"] = true
L["Load All"] = true
L["Load Pack"] = true
L["Load only in Instance"] = true
L["Loadouts"] = true
L["Logo Texture"] = true
L["M"] = true
L["M+ Keystone Level"] = true
L["M+ Score"] = true
L["M+ Season"] = true
L["M+"] = true
L["MAGE"] = true
L["MONK"] = true
L["MS"] = true
L["MaUI XIV Like"] = true
L["Main Professions"] = true
L["Marker Settings"] = true
L["Middle click to open M+ Frame"] = true
L["Misc"] = true
L["Missing"] = true
L["Mobile"] = true
L["Moon"] = true
L["Mounts"] = true
L["Mythic Plus Keystone"] = true
L["Mythic+ Score"] = true
L["N"] = true
L["NEUTRAL"] = true
L["NPC IDS"] = true
L["Name"] = true
L["Nameplates"] = true
L["New:"] = true
L["No Dungeon"] = true
L["No Keystone"] = true
L["No Main Professions"] = true
L["No Professions|r"] = true
L["No Score"] = true
L["No Secondary Professions"] = true
L["No decimal values for percentage."] = true
L["None"] = true
L["Normal Color Style"] = true
L["Not Ready"] = true
L["Notification Color Style"] = true
L["Notification"] = true
L["Objective Tracker"] = true
L["Offline"] = true
L["Optimal size for the logo is 512 x 128 Pixel"] = true
L["Other Colors"] = true
L["Other"] = true
L["Others"] = true
L["Output Audio Device"] = true
L["Output/ Input"] = true
L["Overlay Color"] = true
L["Overlay Texture"] = true
L["PALADIN"] = true
L["PRIEST"] = true
L["Panels"] = true
L["Party"] = true
L["Pet"] = true
L["Pets"] = true
L["Phase Icon"] = true
L["Phase"] = true
L["Phasing"] = true
L["Player"] = true
L["Portrait Offset/ Zoom"] = true
L["Portraits"] = true
L["Position Settings"] = true
L["Power"] = true
L["Professions"] = true
L["Profit:"] = true
L["Progress"] = true
L["Quest Count"] = true
L["Quest Icons"] = true
L["ROGUE"] = true
L["Raidtarget Icons"] = true
L["Rare Border Color"] = true
L["Rare Elite"] = true
L["Rare"] = true
L["Ready Check Icons"] = true
L["Ready Check"] = true
L["Ready"] = true
L["Rejected"] = true
L["Release"] = true
L["ReloadUI"] = true
L["Replace the Unit name with Status Icon, if applicable."] = true
L["Replace the Unit name with Status, if applicable."] = true
L["Reset Character Data: Hold Shift + Right Click"] = true
L["Reset DB"] = true
L["Reset Session Data: Hold Ctrl + Right Click"] = true
L["Reset"] = true
L["Resurrection"] = true
L["Right click to open the ElvUI settings."] = true
L["Role Colors"] = true
L["Role Icons"] = true
L["Roll Button"] = true
L["SHAMAN"] = true
L["Same as"] = true
L["Season has not started yet."] = true
L["Secondary Professions"] = true
L["Select Volume Stream"] = true
L["Server: "] = true
L["Session:"] = true
L["Settings"] = true
L["Shadow Color"] = true
L["Shadow"] = true
L["Shadow/ Border"] = true
L["Sharding"] = true
L["Short Number"] = true
L["Shortened version of abbrev Name of Target."] = true
L["Shortened version of"] = true
L["Show Datatext Icon"] = true
L["Show Great Vault infos in the Tooltip and opens the Great Vault"] = true
L["Show Groupmember Keys."] = true
L["Show Icon"] = true
L["Show Icons"] = true
L["Show Keystone to Chat"] = true
L["Show Max Count"] = true
L["Show Role if in Group"] = true
L["Show Text on Icon"] = true
L["Show Text"] = true
L["Show Welcome text"] = true
L["Show Year"] = true
L["Show amount in Bag"] = true
L["Show only in Combat"] = true
L["Show weekly upgrades"] = true
L["Shows Name"] = true
L["Shows the Healthmarkers only in a Instance"] = true
L["Shows the Weekly Affixes."] = true
L["Shows your Keystone in the tooltip."] = true
L["Size"] = true
L["Skin"] = true
L["Skull"] = true
L["Smart Level changes to resting in resting Areas."] = true
L["Some settings have been changed! For mMediaTag to work properly, a reload of the interface is recommended. Should a reload be performed now?"] = true
L["Sort Methods"] = true
L["Sort"] = true
L["Spent:"] = true
L["Square"] = true
L["Star"] = true
L["Status Colors"] = true
L["Status Icons"] = true
L["Status"] = true
L["Summon Icons"] = true
L["Summon"] = true
L["Tags"] = true
L["Talent Builds"] = true
L["Tank and Healer roles as text."] = true
L["Tank"] = true
L["Target counter (Party and Raid)."] = true
L["Target counter Icon (Flat Circle)."] = true
L["Target counter Icon (Flat Diamond)."] = true
L["Target counter Icon (Flat Square)."] = true
L["Target counter Icon (Flat Stop shield)."] = true
L["Target counter Icon (Glas Circle)."] = true
L["Target counter Icon (Roleicons)."] = true
L["Target of Target"] = true
L["Target"] = true
L["Targetunit colors with mMediaTag colors for Rare, Rareelite, Elite and Boss and Classcolors."] = true
L["Targetunit role icon."] = true
L["Teleports"] = true
L["Text to Instance Name"] = true
L["Text to display"] = true
L["Text"] = true
L["Texture Form"] = true
L["Texture Packs"] = true
L["Texture Style"] = true
L["Texture"] = true
L["Textures"] = true
L["Thanks to:"] = true
L["The ObjectiveTracker settings have been reset to reflect the latest updates in mMT."] = true
L["The position parameters of the ElvUI instance difficulty symbol are used. To change the position, the position of the ElvUI symbol must be changed."] = true
L["These are just examples of how to create your own dock with ElvUI's custom bars.\n\n\nTo create your own bar you have to go to ElvUI under ElvUI>Datatext>Bars Steps 1. enter name press OK and click Add, set the width of the bar depends on how many icons you want to display, the height of the bar is also the size of the icons. Set the number of data text and now you only need to assign the icons to the places, for example 1 = Dock FPS, 2 = Dock Profession and so on.\n\n"] = true
L["This Week Affix"] = true
L["Time until the text disappears"] = true
L["Toggle Volume Stream"] = true
L["Tooltip Icon size."] = true
L["Tooltip Icon"] = true
L["Tooltip Keystone"] = true
L["Tooltip"] = true
L["Total: "] = true
L["Toys"] = true
L["Tracked Achievements"] = true
L["Triangle"] = true
L["Trigger A"] = true
L["Trigger B"] = true
L["Unit colors with mMediaTag colors for Rare and Rareelite."] = true
L["Unit colors with mMediaTag colors for Rare, Rareelite, Elite and Boss and Classcolors."] = true
L["Unit role icon."] = true
L["Unit"] = true
L["Unitframe Icons"] = true
L["Update:"] = true
L["Use Class Icons"] = true
L["Use Default NPC IDs"] = true
L["Use only Default Color"] = true
L["Uses Custom and default NPC IDs"] = true
L["Uses for every Unit the Default Color."] = true
L["Values"] = true
L["Version:"] = true
L["Volume Streams"] = true
L["Volume"] = true
L["WARLOCK"] = true
L["WARRIOR"] = true
L["Waiting"] = true
L["Warmode"] = true
L["Weekly Affixes"] = true
L["Welcome text"] = true
L["White"] = true
L["WoW Token:"] = true
L["World Latency:"] = true
L["X offset"] = true
L["Y offset"] = true
L["Zone"] = true
L["Zooms the texture so we get clean icons without borders."] = true
L["Zzz"] = true
L["and"] = true
L["first Profession"] = true
L["first and second Profession"] = true
L["left click to open LFD Window"] = true
L["left click to open the menu."] = true
L["left click to open the small menu."] = true
L["mCombatTime"] = true
L["mMT Dock"] = true
L["mMT Extra"] = true
L["mMT XIV Like Color"] = true
L["mMT XIV Like"] = true
L["middle click to open the Dungeon Teleports menu."] = true
L["no Status version of"] = true
L["right click to open Great Vault Window"] = true
L["right click to open LFD Window"] = true
L["right click to open the other Teleports menu."] = true
L["second Profession"] = true
L["white Text"] = true
L["white shield Icon"] = true
L["withe Text"] = true
L["withe Value"] = true
L["|cFFffffffLeft Click:|r Select Volume Stream"] = true
L["|cFFffffffMiddle Click:|r Toggle Mute Master Stream"] = true
L["|cFFffffffRight Click:|r Toggle Volume Stream"] = true
L["|cFFffffffShift + Left Click:|r Open System Audio Panel"] = true
L["|cFFffffffShift + Right Click:|r Select Output Audio Device"] = true
L["|cffFFFFFFControl + Left Click:|r Change Loadout"] = true
L["|cffFFFFFFLeft Click:|r Change Talent Specialization"] = true
L["|cffFFFFFFRight Click:|r Change Loot Specialization"] = true
L["|cffFFFFFFShift + Left Click:|r Show Talent Specialization UI"] = true