local E = unpack(ElvUI)
function mMT:Layout_Actionbar()
	E.db["actionbar"]["bar1"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar1"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["countFontSize"] = 12
	E.db["actionbar"]["bar1"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar1"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar1"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar1"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar1"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar1"]["macroFontSize"] = 12
	E.db["actionbar"]["bar1"]["macroTextPosition"] = "BOTTOM"
	E.db["actionbar"]["bar1"]["macrotext"] = true
	E.db["actionbar"]["bar1"]["visibility"] = "[petbattle]  hide; show\n"

	E.db["actionbar"]["bar2"]["buttonHeight"] = 22
	E.db["actionbar"]["bar2"]["buttonSize"] = 36
	E.db["actionbar"]["bar2"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar2"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["countFontSize"] = 12
	E.db["actionbar"]["bar2"]["enabled"] = true
	E.db["actionbar"]["bar2"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar2"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar2"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar2"]["keepSizeRatio"] = false
	E.db["actionbar"]["bar2"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar2"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar2"]["macroFontSize"] = 12
	E.db["actionbar"]["bar2"]["macroTextPosition"] = "BOTTOM"
	E.db["actionbar"]["bar2"]["mouseover"] = true

	E.db["actionbar"]["bar3"]["buttons"] = 12
	E.db["actionbar"]["bar3"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar3"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["countFontSize"] = 12
	E.db["actionbar"]["bar3"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar3"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar3"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar3"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar3"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar3"]["macroFontSize"] = 12
	E.db["actionbar"]["bar3"]["macroTextPosition"] = "BOTTOM"
	E.db["actionbar"]["bar3"]["visibility"] = "[vehicleui] hide; [petbattle] hide; [overridebar] hide; show;"

	E.db["actionbar"]["bar4"]["backdrop"] = false
	E.db["actionbar"]["bar4"]["buttonHeight"] = 22
	E.db["actionbar"]["bar4"]["buttonSize"] = 36
	E.db["actionbar"]["bar4"]["buttonsPerRow"] = 12
	E.db["actionbar"]["bar4"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar4"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["countFontSize"] = 12
	E.db["actionbar"]["bar4"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar4"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar4"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar4"]["keepSizeRatio"] = false
	E.db["actionbar"]["bar4"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar4"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar4"]["macroFontSize"] = 12
	E.db["actionbar"]["bar4"]["macroTextPosition"] = "BOTTOM"
	E.db["actionbar"]["bar4"]["mouseover"] = true

	E.db["actionbar"]["bar5"]["buttons"] = 12
	E.db["actionbar"]["bar5"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar5"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["countFontSize"] = 12
	E.db["actionbar"]["bar5"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar5"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar5"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar5"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar5"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar5"]["macroFontSize"] = 12
	E.db["actionbar"]["bar5"]["macroTextPosition"] = "BOTTOM"
	E.db["actionbar"]["bar5"]["visibility"] = "[vehicleui] hide; [petbattle] hide; [overridebar] hide; show;"

	E.db["actionbar"]["bar6"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar6"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar6"]["countFontSize"] = 12
	E.db["actionbar"]["bar6"]["enabled"] = true
	E.db["actionbar"]["bar6"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar6"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar6"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar6"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar6"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar6"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar6"]["macroTextPosition"] = "BOTTOM"
	E.db["actionbar"]["bar6"]["visibility"] = "[vehicleui] hide; [petbattle] hide; [overridebar] hide; show;"

	E.db["actionbar"]["bar7"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar7"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar7"]["countFontSize"] = 12
	E.db["actionbar"]["bar7"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar7"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar7"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar7"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar7"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar7"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar7"]["macroFontSize"] = 12
	E.db["actionbar"]["bar7"]["macroTextPosition"] = "BOTTOM"

	E.db["actionbar"]["bar8"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar8"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar8"]["countFontSize"] = 12
	E.db["actionbar"]["bar8"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar8"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar8"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar8"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar8"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar8"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar8"]["macroFontSize"] = 12
	E.db["actionbar"]["bar8"]["macroTextPosition"] = "BOTTOM"

	E.db["actionbar"]["bar9"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar9"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar9"]["countFontSize"] = 12
	E.db["actionbar"]["bar9"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar9"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar9"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar9"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar9"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar9"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar9"]["macroFontSize"] = 12
	E.db["actionbar"]["bar9"]["macroTextPosition"] = "BOTTOM"

	E.db["actionbar"]["bar10"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar10"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar10"]["countFontSize"] = 12
	E.db["actionbar"]["bar10"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar10"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar10"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["bar10"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["bar10"]["macroFont"] = "PT Sans Narrow"
	E.db["actionbar"]["bar10"]["macroFontOutline"] = "OUTLINE"
	E.db["actionbar"]["bar10"]["macroFontSize"] = 12
	E.db["actionbar"]["bar10"]["macroTextPosition"] = "BOTTOM"

	E.db["actionbar"]["barPet"]["backdrop"] = false
	E.db["actionbar"]["barPet"]["buttonHeight"] = 24
	E.db["actionbar"]["barPet"]["buttonsPerRow"] = 10
	E.db["actionbar"]["barPet"]["countFont"] = "PT Sans Narrow"
	E.db["actionbar"]["barPet"]["countFontOutline"] = "OUTLINE"
	E.db["actionbar"]["barPet"]["countFontSize"] = 12
	E.db["actionbar"]["barPet"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["barPet"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["barPet"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["barPet"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["barPet"]["keepSizeRatio"] = false

	E.db["actionbar"]["chargeCooldown"] = true
	E.db["actionbar"]["cooldown"]["override"] = false
	E.db["actionbar"]["desaturateOnCooldown"] = true
	E.db["actionbar"]["equippedItem"] = true
	E.db["actionbar"]["extraActionButton"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["extraActionButton"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["extraActionButton"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["extraActionButton"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["extraActionButton"]["scale"] = 0.6
	E.db["actionbar"]["flashAnimation"] = true
	E.db["actionbar"]["font"] = "PT Sans Narrow"
	E.db["actionbar"]["fontOutline"] = "OUTLINE"
	E.db["actionbar"]["fontSize"] = 12
	E.db["actionbar"]["globalFadeAlpha"] = 1
	E.db["actionbar"]["macroTextPosition"] = "BOTTOM"
	E.db["actionbar"]["stanceBar"]["buttonHeight"] = 24
	E.db["actionbar"]["stanceBar"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["stanceBar"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["stanceBar"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["stanceBar"]["hotkeyTextXOffset"] = 1
	E.db["actionbar"]["stanceBar"]["inheritGlobalFade"] = true
	E.db["actionbar"]["transparent"] = true
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFont"] = "PT Sans Narrow"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontOutline"] = "OUTLINE"
	E.db["actionbar"]["vehicleExitButton"]["hotkeyFontSize"] = 12
	E.db["actionbar"]["vehicleExitButton"]["hotkeyTextYOffset"] = -4
	E.db["actionbar"]["zoneActionButton"]["scale"] = 0.6
end

function mMT:Layout_Auras()
	E.db["auras"]["buffs"]["barColorGradient"] = true
	E.db["auras"]["buffs"]["barSize"] = 4
	E.db["auras"]["buffs"]["barSpacing"] = 1
	E.db["auras"]["buffs"]["barTexture"] = "mMediaTag R1"
	E.db["auras"]["buffs"]["countFont"] = "PT Sans Narrow"
	E.db["auras"]["buffs"]["countFontOutline"] = "OUTLINE"
	E.db["auras"]["buffs"]["countFontSize"] = 12
	E.db["auras"]["buffs"]["countYOffset"] = 2
	E.db["auras"]["buffs"]["horizontalSpacing"] = 2
	E.db["auras"]["buffs"]["seperateOwn"] = 0
	E.db["auras"]["buffs"]["size"] = 40
	E.db["auras"]["buffs"]["timeFont"] = "PT Sans Narrow"
	E.db["auras"]["buffs"]["timeFontOutline"] = "OUTLINE"
	E.db["auras"]["buffs"]["timeFontSize"] = 14
	E.db["auras"]["buffs"]["timeYOffset"] = 8
	E.db["auras"]["buffs"]["verticalSpacing"] = 20
	E.db["auras"]["buffs"]["wrapAfter"] = 14

	E.db["auras"]["debuffs"]["barColorGradient"] = true
	E.db["auras"]["debuffs"]["barNoDuration"] = false
	E.db["auras"]["debuffs"]["barSize"] = 4
	E.db["auras"]["debuffs"]["barSpacing"] = 1
	E.db["auras"]["debuffs"]["barTexture"] = "mMediaTag R1"
	E.db["auras"]["debuffs"]["countFont"] = "PT Sans Narrow"
	E.db["auras"]["debuffs"]["countFontOutline"] = "OUTLINE"
	E.db["auras"]["debuffs"]["countFontSize"] = 14
	E.db["auras"]["debuffs"]["countYOffset"] = 8
	E.db["auras"]["debuffs"]["horizontalSpacing"] = 2
	E.db["auras"]["debuffs"]["seperateOwn"] = 0
	E.db["auras"]["debuffs"]["size"] = 40
	E.db["auras"]["debuffs"]["timeFont"] = "PT Sans Narrow"
	E.db["auras"]["debuffs"]["timeFontOutline"] = "OUTLINE"
	E.db["auras"]["debuffs"]["timeFontSize"] = 12
	E.db["auras"]["debuffs"]["timeXOffset"] = 2
	E.db["auras"]["debuffs"]["verticalSpacing"] = 20
	E.db["auras"]["debuffs"]["wrapAfter"] = 14
end

function mMT:Layout_Bags()
	E.db["bags"]["bagSize"] = 32
	E.db["bags"]["bagWidth"] = 534
	E.db["bags"]["bankSize"] = 32
	E.db["bags"]["bankWidth"] = 534
	E.db["bags"]["clearSearchOnClose"] = true
	E.db["bags"]["countFont"] = "PT Sans Narrow"
	E.db["bags"]["countFontOutline"] = "OUTLINE"
	E.db["bags"]["countFontSize"] = 12
	E.db["bags"]["currencyFormat"] = "ICON_TEXT"
	E.db["bags"]["itemInfoFont"] = "PT Sans Narrow"
	E.db["bags"]["itemInfoFontOutline"] = "OUTLINE"
	E.db["bags"]["itemInfoFontSize"] = 12
	E.db["bags"]["itemLevelFont"] = "PT Sans Narrow"
	E.db["bags"]["itemLevelFontOutline"] = "OUTLINE"
	E.db["bags"]["itemLevelFontSize"] = 12
	E.db["bags"]["junkDesaturate"] = true
	E.db["bags"]["junkIcon"] = true
	E.db["bags"]["moneyFormat"] = "BLIZZARD"
	E.db["bags"]["scrapIcon"] = true
	E.db["bags"]["showBindType"] = true
	E.db["bags"]["split"]["bag5"] = true
	E.db["bags"]["split"]["bagSpacing"] = 6
	E.db["bags"]["split"]["player"] = true
	E.db["bags"]["transparent"] = true
	E.db["bags"]["vendorGrays"]["details"] = true
	E.db["bags"]["vendorGrays"]["enable"] = true
end

function mMT:Layout_Chat()
	E.db["chat"]["copyChatLines"] = true
	E.db["chat"]["customTimeColor"]["b"] = 0
	E.db["chat"]["customTimeColor"]["g"] = 0.7843137254902
	E.db["chat"]["customTimeColor"]["r"] = 1
	E.db["chat"]["fontSize"] = 12
	E.db["chat"]["keywordSound"] = "Whisper Alert"
	E.db["chat"]["keywords"] = "ElvUI, %MYNAME%"
	E.db["chat"]["maxLines"] = 200
	E.db["chat"]["noAlertInCombat"] = true
	E.db["chat"]["numScrollMessages"] = 1
	E.db["chat"]["panelBackdropNameLeft"] = "Interface\\Addons\\!mMT_MediaPack\\media\\backgrounds\\chat4.tga"
	E.db["chat"]["panelBackdropNameRight"] = "Interface\\Addons\\!mMT_MediaPack\\media\\backgrounds\\chat3.tga"
	E.db["chat"]["panelColor"]["a"] = 0.49999934434891
	E.db["chat"]["panelColor"]["b"] = 0.094117656350136
	E.db["chat"]["panelColor"]["g"] = 0.094117656350136
	E.db["chat"]["panelColor"]["r"] = 0.13333334028721
	E.db["chat"]["panelHeight"] = 160
	E.db["chat"]["panelTabTransparency"] = true
	E.db["chat"]["panelWidth"] = 454
	E.db["chat"]["socialQueueMessages"] = true
	E.db["chat"]["tabSelector"] = "BOX"
	E.db["chat"]["timeStampFormat"] = "%H:%M "
end

function mMT:Layout_Misc()
	E.db["convertPages"] = true
	E.db["cooldown"]["fonts"]["enable"] = true
	E.db["cooldown"]["fonts"]["fontSize"] = 16
	E.db["cooldown"]["hhmmColor"]["b"] = 1
	E.db["cooldown"]["hhmmColor"]["g"] = 1
	E.db["cooldown"]["hhmmColor"]["r"] = 0.4
	E.db["cooldown"]["mmssColor"]["b"] = 1
	E.db["cooldown"]["mmssColor"]["g"] = 1
	E.db["cooldown"]["mmssColor"]["r"] = 1
end

function mMT:Layout_Databars()
	E.db["databars"]["azerite"]["enable"] = false
	E.db["databars"]["azerite"]["height"] = 5
	E.db["databars"]["azerite"]["orientation"] = "HORIZONTAL"
	E.db["databars"]["azerite"]["showBubbles"] = true
	E.db["databars"]["azerite"]["width"] = 176
	E.db["databars"]["colors"]["factionColors"][1]["b"] = 0.04313725605607
	E.db["databars"]["colors"]["factionColors"][1]["g"] = 0
	E.db["databars"]["colors"]["factionColors"][1]["r"] = 1
	E.db["databars"]["colors"]["factionColors"][2]["b"] = 0.34901961684227
	E.db["databars"]["colors"]["factionColors"][2]["g"] = 0
	E.db["databars"]["colors"]["factionColors"][2]["r"] = 1
	E.db["databars"]["colors"]["factionColors"][3]["g"] = 0.37647062540054
	E.db["databars"]["colors"]["factionColors"][3]["r"] = 1
	E.db["databars"]["colors"]["factionColors"][4]["g"] = 0.57254904508591
	E.db["databars"]["colors"]["factionColors"][4]["r"] = 1
	E.db["databars"]["colors"]["factionColors"][5]["b"] = 0.44313728809357
	E.db["databars"]["colors"]["factionColors"][5]["g"] = 1
	E.db["databars"]["colors"]["factionColors"][5]["r"] = 0.050980396568775
	E.db["databars"]["colors"]["factionColors"][6]["b"] = 0.21960785984993
	E.db["databars"]["colors"]["factionColors"][6]["g"] = 1
	E.db["databars"]["colors"]["factionColors"][7]["b"] = 0
	E.db["databars"]["colors"]["factionColors"][7]["g"] = 1
	E.db["databars"]["colors"]["factionColors"][7]["r"] = 0.15686275064945
	E.db["databars"]["colors"]["factionColors"][8]["b"] = 0
	E.db["databars"]["colors"]["factionColors"][8]["g"] = 1
	E.db["databars"]["colors"]["factionColors"][8]["r"] = 0.49411767721176
	E.db["databars"]["colors"]["factionColors"][9]["b"] = 1
	E.db["databars"]["colors"]["factionColors"][9]["g"] = 0
	E.db["databars"]["colors"]["factionColors"][9]["r"] = 0.61960786581039
	E.db["databars"]["colors"]["quest"]["a"] = 0.60532039403915
	E.db["databars"]["colors"]["quest"]["r"] = 0.35686274509804
	E.db["databars"]["colors"]["useCustomFactionColors"] = true
	E.db["databars"]["customTexture"] = true
	E.db["databars"]["experience"]["height"] = 16
	E.db["databars"]["experience"]["hideInCombat"] = true
	E.db["databars"]["experience"]["orientation"] = "HORIZONTAL"
	E.db["databars"]["experience"]["questCompletedOnly"] = true
	E.db["databars"]["experience"]["questTrackedOnly"] = true
	E.db["databars"]["experience"]["showBubbles"] = true
	E.db["databars"]["experience"]["textFormat"] = "CURPERC"
	E.db["databars"]["experience"]["width"] = 406
	E.db["databars"]["experience"]["yOffset"] = -1
	E.db["databars"]["honor"]["fontSize"] = 12
	E.db["databars"]["honor"]["hideBelowMaxLevel"] = true
	E.db["databars"]["honor"]["orientation"] = "HORIZONTAL"
	E.db["databars"]["honor"]["width"] = 182
	E.db["databars"]["honor"]["yOffset"] = -1
	E.db["databars"]["reputation"]["enable"] = true
	E.db["databars"]["reputation"]["fontSize"] = 12
	E.db["databars"]["reputation"]["orientation"] = "HORIZONTAL"
	E.db["databars"]["reputation"]["width"] = 182
	E.db["databars"]["reputation"]["yOffset"] = -1
	E.db["databars"]["statusbar"] = "mMediaTag R1"
	E.db["databars"]["threat"]["enable"] = false
	E.db["databars"]["threat"]["fontSize"] = 14
	E.db["databars"]["threat"]["height"] = 16
	E.db["databars"]["threat"]["width"] = 406
	E.db["databars"]["threat"]["yOffset"] = -1
end
