E.global["datatexts"]["customPanels"]["MaUI Cosmatic Bar Left"]["height"] = 12
E.global["datatexts"]["customPanels"]["MaUI Cosmatic Bar Left"]["name"] = "MaUI Cosmatic Bar Left"
E.global["datatexts"]["customPanels"]["MaUI Cosmatic Bar Left"]["numPoints"] = 1
E.global["datatexts"]["customPanels"]["MaUI Cosmatic Bar Left"]["visibility"] = ""
E.global["datatexts"]["customPanels"]["MaUI Cosmatic Bar Left"]["width"] = 202
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Center"]["height"] = 12
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Center"]["name"] = "MaUI Cosmetic Bar Center"
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Center"]["numPoints"] = 1
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Center"]["width"] = 406
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Right"]["height"] = 12
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Right"]["name"] = "MaUI Cosmetic Bar Right"
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Right"]["numPoints"] = 1
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Right"]["visibility"] = ""
E.global["datatexts"]["customPanels"]["MaUI Cosmetic Bar Right"]["width"] = 202
E.global["datatexts"]["customPanels"]["MaUI Left"]["backdrop"] = false
E.global["datatexts"]["customPanels"]["MaUI Left"]["height"] = 32
E.global["datatexts"]["customPanels"]["MaUI Left"]["name"] = "MaUI Left"
E.global["datatexts"]["customPanels"]["MaUI Left"]["numPoints"] = 12
E.global["datatexts"]["customPanels"]["MaUI Left"]["textJustify"] = "LEFT"
E.global["datatexts"]["customPanels"]["MaUI Left"]["width"] = 460
E.global["datatexts"]["customPanels"]["MaUI Right"]["backdrop"] = false
E.global["datatexts"]["customPanels"]["MaUI Right"]["fonts"]["enable"] = true
E.global["datatexts"]["customPanels"]["MaUI Right"]["fonts"]["fontOutline"] = "SHADOW"
E.global["datatexts"]["customPanels"]["MaUI Right"]["fonts"]["fontSize"] = 16
E.global["datatexts"]["customPanels"]["MaUI Right"]["height"] = 32
E.global["datatexts"]["customPanels"]["MaUI Right"]["name"] = "MaUI Right"
E.global["datatexts"]["customPanels"]["MaUI Right"]["numPoints"] = 4
E.global["datatexts"]["customPanels"]["MaUI Right"]["textJustify"] = "RIGHT"
E.global["datatexts"]["customPanels"]["MaUI Right"]["width"] = 460
E.global["datatexts"]["customPanels"]["MaUI Time"]["backdrop"] = false
E.global["datatexts"]["customPanels"]["MaUI Time"]["fonts"]["enable"] = true
E.global["datatexts"]["customPanels"]["MaUI Time"]["fonts"]["fontOutline"] = "SHADOW"
E.global["datatexts"]["customPanels"]["MaUI Time"]["fonts"]["fontSize"] = 32
E.global["datatexts"]["customPanels"]["MaUI Time"]["height"] = 32
E.global["datatexts"]["customPanels"]["MaUI Time"]["name"] = "MaUI Time"
E.global["datatexts"]["customPanels"]["MaUI Time"]["numPoints"] = 1
E.global["datatexts"]["customPanels"]["MaUI Time"]["width"] = 128
E.global["datatexts"]["customPanels"]["MaUI Time Left"]["backdrop"] = false
E.global["datatexts"]["customPanels"]["MaUI Time Left"]["fonts"]["enable"] = true
E.global["datatexts"]["customPanels"]["MaUI Time Left"]["fonts"]["fontOutline"] = "SHADOW"
E.global["datatexts"]["customPanels"]["MaUI Time Left"]["fonts"]["fontSize"] = 16
E.global["datatexts"]["customPanels"]["MaUI Time Left"]["height"] = 32
E.global["datatexts"]["customPanels"]["MaUI Time Left"]["name"] = "MaUI Time Left"
E.global["datatexts"]["customPanels"]["MaUI Time Left"]["numPoints"] = 2
E.global["datatexts"]["customPanels"]["MaUI Time Left"]["width"] = 430
E.global["datatexts"]["customPanels"]["MaUI Time Right"]["backdrop"] = false
E.global["datatexts"]["customPanels"]["MaUI Time Right"]["fonts"]["enable"] = true
E.global["datatexts"]["customPanels"]["MaUI Time Right"]["fonts"]["fontOutline"] = "SHADOW"
E.global["datatexts"]["customPanels"]["MaUI Time Right"]["fonts"]["fontSize"] = 16
E.global["datatexts"]["customPanels"]["MaUI Time Right"]["height"] = 32
E.global["datatexts"]["customPanels"]["MaUI Time Right"]["name"] = "MaUI Time Right"
E.global["datatexts"]["customPanels"]["MaUI Time Right"]["numPoints"] = 2
E.global["datatexts"]["customPanels"]["MaUI Time Right"]["width"] = 430
E.global["datatexts"]["customPanels"]["mMT Combattime"]["backdrop"] = false
E.global["datatexts"]["customPanels"]["mMT Combattime"]["border"] = false
E.global["datatexts"]["customPanels"]["mMT Combattime"]["fonts"]["enable"] = true
E.global["datatexts"]["customPanels"]["mMT Combattime"]["fonts"]["fontOutline"] = "SHADOW"
E.global["datatexts"]["customPanels"]["mMT Combattime"]["fonts"]["fontSize"] = 32
E.global["datatexts"]["customPanels"]["mMT Combattime"]["height"] = 32
E.global["datatexts"]["customPanels"]["mMT Combattime"]["name"] = "mMT Combattime"
E.global["datatexts"]["customPanels"]["mMT Combattime"]["numPoints"] = 1
E.global["datatexts"]["customPanels"]["mMT Combattime"]["width"] = 188
E.global["datatexts"]["settings"]["Armor"]["NoLabel"] = true
E.global["datatexts"]["settings"]["Combat"]["TimeFull"] = false
E.global["datatexts"]["settings"]["Currencies"]["displayedCurrency"] = "1191"
E.global["datatexts"]["settings"]["Currencies"]["goldFormat"] = "SHORTSPACED"
E.global["datatexts"]["settings"]["Currencies"]["headers"] = false
E.global["datatexts"]["settings"]["Currencies"]["idEnable"][1166] = true
E.global["datatexts"]["settings"]["Durability"]["percThreshold"] = 40
E.global["datatexts"]["settings"]["Experience"]["textFormat"] = "PERCENT"
E.global["datatexts"]["settings"]["Gold"]["goldFormat"] = "SHORTSPACED"
E.global["datatexts"]["settings"]["System"]["NoLabel"] = true
E.globaL["ALL_GENERAL"]["WorldMapCoordinates"]["position"] = "BOTTOMRIGHT"
E.globaL["ALL_GENERAL"]["commandBarSetting"] = "DISABLED"
E.globaL["ALL_GENERAL"]["fadeMapDuration"] = 0.1
E.globaL["ALL_GENERAL"]["mapAlphaWhenMoving"] = 0.35
E.globaL["ALL_GENERAL"]["smallerWorldMap"] = false
E.globaL["ALL_GENERAL"]["smallerWorldMapScale"] = 1
