E.private["general"]["chatBubbleFontOutline"] = "OUTLINE"
E.private["general"]["chatBubbleFontSize"] = 10
E.private["general"]["chatBubbles"] = "disabled"
E.private["general"]["dmgfont"] = "PT Sans Narrow"
E.private["general"]["glossTex"] = "Solid"
E.private["general"]["minimap"]["hideTracking"] = true
E.private["general"]["namefont"] = "PT Sans Narrow"
E.private["general"]["normTex"] = "Solid"
E.private["install_complete"] = 13.42
E.private["theme"] = "class"
